### ISSUE TITLE
Kawakami Finance KKI

### ISSUE THREAD

**Issue by gplates1** [pancakeswap/pancake-document#18]
Hey I bought 517 KKI not too long ago but received only 5.17 KKI. Many other users have the same issue. Pancakeswap was showing 517 on the exchangebut received only 5.17
Also the value of these coins was not what I paid for. It's the same 1/100 of what it should be.

**Comment by ChefNina** [comment]
PancakeSwap exchange shows how much token you'll get at the point of router transaction. After that, token contract will be called, in your case it's KKI. They charge you 90~99 % liquidity fee.
Please find the warning I tweeted. 
https://twitter.com/_ninahaus_EN/status/1413677345769144322?s=20
