### ISSUE TITLE
Prediction issue

### ISSUE THREAD

**Issue by AliHass51214** [pancakeswap/pancake-document#27]
My winning didn't showed in history even after almost more than 30mins passed

**Comment by AliHass51214** [comment]
I have participated first time in prediction of bnb but got no result in history or pnl... Why is that? Can anyone help please?

**Comment by ChefNina** [comment]
Hi @AliHass51214 
Sorry for late response, this is the incorrect place to ask such question, please ask it in our telegram channel.
