### ISSUE TITLE
Execution reverted 

### ISSUE THREAD

**Issue by Carloscol8** [pancakeswap/pancake-document#32]
Hi I'm trying to swap BNB to Cryptozoo, but everytime I get the same error, I did what the, FQa, say, and its the same. 
![IMG_20210830_223801](https://user-images.githubusercontent.com/89810114/131402309-7b0be6d8-d90c-423d-a773-053d9febc637.jpg)

**Comment by ChefNina** [comment]
Hi @Carloscol8,
This is the incorrect place to ask such question, please ask it in our telegram channel.
