### ISSUE TITLE
Cant change

### ISSUE THREAD

**Issue by hosein83ei** [pancakeswap/pancake-document#33]
Hi i cant chang my coin mneb please help me

**Comment by ChefNina** [comment]
Hi @hosein83ei 
This is the incorrect place to ask such question, please ask it in our telegram channel.

**Comment by hosein83ei** [comment]
Send me id

در تاریخ پنجشنبه ۹ سپتامبر ۲۰۲۱،‏ ۲:۴۱ Chef Nina ***@***.***>
نوشت:

**Comment by ScottRichNetworks** [comment]
Lost coins in swaps. Seem to not be able to recover?
