### ISSUE TITLE
[BUG] Images are broken urls on liquidity-guide

### ISSUE THREAD

**Issue by R-K-H** [pancakeswap/pancake-document#35]
https://docs.pancakeswap.finance/products/pancakeswap-exchange/liquidity-guide

Visit this link and you'll see all images are broken.

RE: https://old.reddit.com/r/pancakeswap/comments/pp082x/can_someone_fix_images_in_the_how_to_addremove/

**Comment by ChefNina** [comment]
Hello @R-K-H 
We are aware of it and will work on fixing. Thanks for reporting.

**Comment by willmacdonald** [comment]
Images are working now.

**Comment by ChefNina** [comment]
This issue has been resolved!
