### ISSUE TITLE
[Security issue] Restart the computer and still can see the account information

### ISSUE THREAD

**Issue by cakkkk777** [pancakeswap/pancake-document#37]
Steps to reproduce the bug: 
1. Visit the pancakeswap website, open the Trust Wallet APP, scan the WalletConnect QR code, and successfully connect to Trust Wallet.
2. After a few minutes, close the pancakeswap page.
3. Restart the computer.
4. Visit the pancakeswap website and check my truste wallet application. Make sure there is no connection working.
5. BUT pancakeswap website can access my trusted wallet without my authorization! ! ! 
6. An error message appears the console when refreshing the website, the error message "Uncaught (in promise) Error: unknown account #0 (operation="getAddress", code=UNSUPPORTED_OPERATION, version=providers/5.4.1)
    at e.value (3.c2d5a211.chunk.js:1)
    at e.value (3.c2d5a211.chunk.js:1)
    at 3.c2d5a211.chunk.js:1
    at async Promise.all (index 0)"

This is indeed a big security issue. There are no active connections in my wallet, but the website can display personal data. And the recent CAKE profit balance data has been constantly changing, consistent with the latest profit data.

![241500144_929091627964451_1791655786666375835_n](https://user-images.githubusercontent.com/91197553/134344085-cac03711-ab0a-4e76-9f06-940efcb75f4c.jpeg)
![242192457_613225153038727_8319789236007159144_n](https://user-images.githubusercontent.com/91197553/134344093-b2785369-3f39-4a7c-9f40-13a918d5a0a8.jpeg)
![242712150_658801298427129_2468885087950441304_n](https://user-images.githubusercontent.com/91197553/134344099-7a3bf094-4e3d-4291-8782-b5b6d8cc07a1.jpeg)

**Comment by cakkkk777** [comment]
The wallet id put in the browser Local storage. Is it safe?????
Why don't you put in session storage?????

**Comment by ChefNina** [comment]
Hi @cakkkk777 
You raised this issue in the wrong repository, this is the place for documentation.
Please recreate it in the corresponding place.
