### ISSUE TITLE
Math error in Pools example

### ISSUE THREAD

**Issue by untr0py** [pancakeswap/pancake-document#6]
In the example provided, the 10 FLIP tokens represent 10.017 CAKE and 10.017 BNB after the example trades.
The page then states that

> Each FLIP token is now worth 1.00017 CAKE + 1.00017 BNB.

By my math, each FLIP token should be worth  1.0017 CAKE + 1.0017 BNB.

**Comment by untr0py** [comment]
The page that I'm referring to is here:
https://github.com/pancakeswap/pancake-document/blob/master/core-products/pancakeswap-pools.md

**Comment by komoto12** [comment]
Good Day sir/maam

I want to ask my LP tokens on dxsale is already unlocked .
But if I check it on pancakeswap to remove my liquidity it cant show .

Can you help me with that .
Thankyou 🙏🏻

This is my Token Address.
MinisMonster
0x534cd34bcfd0651390e1ada3e82bc842221d7489

This is my LP address
0x3027B559ef2442eDE023AEdD083eCFA735Be8618


Sent from Android device

**Comment by ChefNina** [comment]
Our doc site has been updated a lot since this question posted. Let me close it as outdated.

**Comment by untr0py** [comment]
How is this outdated @ChefNina? The line in question is still live at this URL:
https://docs.pancakeswap.finance/products/pancakeswap-exchange/pancakeswap-pools
