### ISSUE TITLE
Pancake Factory Address Needs To Be Updated.

### ISSUE THREAD

**Issue by preston4896** [pancakeswap/pancake-document#8]
I noticed on the docs from https://docs.pancakeswap.finance/#is-pancakeswap-safe, it says the verified address for the Pancake Factory Contract is [`0xBCfCcbde45cE874adCB698cC183deBcF17952812`](0xBCfCcbde45cE874adCB698cC183deBcF17952812). (or, verified contract 3)

But as I am reading the code from the [Pancake Router Contract](https://bscscan.com/address/0x10ED43C718714eb63d5aA57B78B54704E256024E#readContract) (redirected by clicking on verified contract 1). The `factory()` method returns the address `0xca143ce32fe78f1f7019d7d551a6402fc5350c73`.  

The inconsistency of factory addresses has caused my app to not being able to locate the pair address of a liquidity pool. I was wondering if the Pancake Factory implementation has been migrated to `0xca143ce32fe78f1f7019d7d551a6402fc5350c73`, and perhaps the docs are not being updated to reflect these changes?

See screenshots for more info:

![factorywrong](https://user-images.githubusercontent.com/23372253/122170983-c7b51a00-ceb1-11eb-9fce-bde78ddde0dd.png)

![factory](https://user-images.githubusercontent.com/23372253/122171268-1bbffe80-ceb2-11eb-88d1-4b646d67cf33.png)

Any insight is appreciated. :)

**Comment by ChefNina** [comment]
Hi @preston4896 
Sorry for late response. It has been updated! 
https://docs.pancakeswap.finance/code/smart-contracts/pancakeswap-exchange/factory-v2
